### ISSUE TITLE
add link the hosted html

### ISSUE THREAD

**Issue by awalterschulze** [coq-community/coq-art#14]
I saw this repo contained html files, but I couldn't find the link to the where it was hosted.
I took a chance and hacked the github url https://coq-community.github.io/coq-art/
Maybe I just missed it and it already is somewhere obvious, but is it possible to add the link to the top of the readme or the project description or about section?

Thank you for maintaining this.
A group of us are finding this repo very useful.

**Comment by ybertot** [comment]
It seems the address should be https://coq-community.org/coq-art

**Comment by awalterschulze** [comment]
Thank you for an amazing book.
It strikes the perfect balance between approachable and going deep enough to be practical.

**Comment by palmskog** [comment]
The reason the canonical link to the deployed HTML (`coq-community.org`) is not mentioned is that the website doesn't give a very nice experience currently. Specifically, all links to Coq files lead to an unfriendly download prompt. For this reason, I would recommend browsing the HTML locally (after cloning the repo).

@ybertot there are some options for improving the deployed HTML (e.g., linking to coqdoc), but it's not obvious which solution is preferable. We can discuss at some point.

**Comment by awalterschulze** [comment]
Even though the downloading of the file is not perfect, the hosted html provides a pretty good experience, in my opinion.  At least I found it useful and per chance downloading the file is exactly what I wanted to happen, but understand that this is not perfect for everyone.

**Comment by Casteran** [comment]
It looks like the following link leads directly to an  index.html 


https://coq-community.org/coq-art/ <https://coq-community.org/coq-art/>

On the other hand, the following link leads to a correct gitHub page (with a problem: the links to html files from README.md show uninterpreted html code)
 
https://github.com/coq-community/coq-art/ <https://github.com/coq-community/coq-art/>

Is there a way to fix that ?

**Comment by awalterschulze** [comment]
github won't interpret the html or javascript when just browsing through files.  The only way AFAIK is to use the hosted github site,  https://coq-community.github.io/coq-art/ , which seems to work really well in my opinion.

**Comment by palmskog** [comment]
The link to the hosted website is now available in both the README and the repo description, so closing.
