### ISSUE TITLE
broken link in ch13_co_inductive_types

### ISSUE THREAD

**Issue by awalterschulze** [coq-community/coq-art#15]
At the top of https://coq-community.org/coq-art/ch13_co_inductive_types/index.html

```
The chapter on co-inductive types of our book is mainly illustrated with the theory of finite or infinite ("lazy") lists. **This file** contains the complete development of this theory. 
```

`This file` links to https://coq-community.org/coq-art/ch13_co_inductive_types/SRC/Coinduc.v which gives a 404

**Comment by ybertot** [comment]
The file Coinduc.v is nowhere to be found in the repository.  As a work around, you can use the following pointer:

https://www.labri.fr/perso/casteran/CoqArt/co-inductifs/SRC/Coinduc.v

The link wil be fixed.

**Comment by Casteran** [comment]
Hi, sorry for this error !

The real name of the file is ch13_co_inductive_types/SRC/chap13.v (on the coq-community repo).
We will have to write a new README.md instead of the old index.html.

Pierre

**Comment by awalterschulze** [comment]
No problem, just thought I'd report it, so it can be fixed for future readers.
I am finding work arounds, don't worry about me.

**Comment by palmskog** [comment]
Fixed, so closing.
