### ISSUE TITLE
Repository organization for different Coq versions?

### ISSUE THREAD

**Issue by palmskog** [coq-community/coq-art#2]
I believe this repository will create the most value when the default branch (when browsing GitHub and cloning) supports the latest stable Coq version. This is in contrast to many other Coq projects, where the default branch (typically `master`) supports the development branch of Coq, i.e., Coq's `master`.

At the same time, I don't believe it's desirable to try to support as many Coq versions as possible in one branch either, since pedagogical conventions and idioms may change across versions, and I think the sources here should follow "recent" conventions (and even serve as documentation for past conventions).

Hence, one way to organize the project may be to have named branches like Coq plugins (e.g., `v8.9`, `v8.10`), but without a `master` branch, and have the latest stable version branch set as the default branch.

So for example, we could rename `master` to `v8.9`, and then eventually create a `v8.10` branch but only set it as default when 8.10.0 is released.

@Zimmi48 what do you think about this idea?

**Comment by Zimmi48** [comment]
The whole point of a repository containing several public branches, as opposed to a single branch and possibly many tags, is to be able to maintain several versions at the same time. If that's the idea here (for instance to be able to maintain branches for upcoming versions of Coq, and the latest stable version), then your idea makes sense indeed. The `v8.X` schema has the interest of being very common in the Coq ecosystem, and being quite readable. GitHub makes it easy to change the default branch of a repository, although it may be a bit weird to do it so regularly...
